---
- hosts: localhost
  gather_facts: no
  tasks:
     - name: pulling docker image
       docker_image:
         name: httpd
         source: pull
     - name: creating a container
       docker_container:
         name: httpd
         image: httpd
         state: started
         detach: yes

